# Generated by Django 4.1 on 2023-05-12 23:47

import booking.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Please enter a valid email address in the format"
                            ),
                            django.core.validators.RegexValidator(
                                inverse_match=True,
                                message="Please provide a valid email address.",
                                regex="^name@name.name",
                            ),
                        ],
                    ),
                ),
                ("birth_date", models.DateField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Non-Binary", "Non-Binary"),
                            ("Prefer Not To Say", "Prefer Not To Say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone_no", models.IntegerField()),
                (
                    "account_type",
                    models.CharField(default="PATIENT", editable=False, max_length=10),
                ),
                (
                    "kin_name",
                    models.CharField(
                        blank=True, help_text="Optional", max_length=50, null=True
                    ),
                ),
                (
                    "kin_contact",
                    models.IntegerField(blank=True, help_text="Optional", null=True),
                ),
                (
                    "password",
                    models.CharField(
                        default="password",
                        max_length=30,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=8,
                                message="Please ensure the password is at least 8 characters",
                            ),
                            django.core.validators.RegexValidator(
                                inverse_match=True,
                                message="Please use a different password",
                                regex="^password",
                            ),
                        ],
                    ),
                ),
                ("is_staff", models.BooleanField(default=False, editable=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_update",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", booking.models.PatientManager()),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(blank=True, max_length=2, null=True, unique=True),
                ),
                (
                    "password",
                    models.CharField(
                        default="password",
                        max_length=30,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=8,
                                message="Please ensure the password is at least 8 characters",
                            ),
                            django.core.validators.RegexValidator(regex="/password"),
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        default="name@name.name",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Please enter a valid email address in the format"
                            )
                        ],
                    ),
                ),
                (
                    "phone_no",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Please enter a 10-digit number",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "account_type",
                    models.CharField(default="DOCTOR", editable=False, max_length=10),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("1", "Adult Cardiology"),
                            ("2", "Adult Neurology"),
                            ("3", "Anaesthesia"),
                            ("4", "Anaesthesia and Critical Care Medicine"),
                            ("5", "Dermatology"),
                            ("6, Nose and Throat (ENT)", "Ear, Nose and Throat (ENT)"),
                            ("7", "General Surgery"),
                            ("8", "Gynaecology / Laparoscopic / Obsterics"),
                            ("9", "Nephrology"),
                            ("10", "Ophthalmologist"),
                            ("11", "Paediatrics and Child Health"),
                            ("12", "Pain Management"),
                            ("13", "Physician /Internal Medicine"),
                            ("14", "Radiology"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/%Y/%m/%d/"
                    ),
                ),
                ("last_login", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "app_id",
                    models.BigAutoField(default="0", primary_key=True, serialize=False),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("1", "Adult Cardiology"),
                            ("2", "Adult Neurology"),
                            ("3", "Anaesthesia"),
                            ("4", "Anaesthesia and Critical Care Medicine"),
                            ("5", "Dermatology"),
                            ("6, Nose and Throat (ENT)", "Ear, Nose and Throat (ENT)"),
                            ("7", "General Surgery"),
                            ("8", "Gynaecology / Laparoscopic / Obsterics"),
                            ("9", "Nephrology"),
                            ("10", "Ophthalmologist"),
                            ("11", "Paediatrics and Child Health"),
                            ("12", "Pain Management"),
                            ("13", "Physician /Internal Medicine"),
                            ("14", "Radiology"),
                        ],
                        default="Physician / Internal Medicine",
                        max_length=50,
                    ),
                ),
                ("day", models.DateField(default=datetime.datetime.now)),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("3 PM", "3 PM"),
                            ("3:30 PM", "3:30 PM"),
                            ("4 PM", "4 PM"),
                            ("4:30 PM", "4:30 PM"),
                            ("5 PM", "5 PM"),
                            ("5:30 PM", "5:30 PM"),
                            ("6 PM", "6 PM"),
                            ("6:30 PM", "6:30 PM"),
                            ("7 PM", "7 PM"),
                            ("7:30 PM", "7:30 PM"),
                        ],
                        default="3 PM",
                        max_length=10,
                    ),
                ),
                (
                    "time_ordered",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("note", models.TextField(max_length=255, null=True)),
                (
                    "uuid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
