# Generated by Django 4.1 on 2023-05-11 15:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Doctor care", "Doctor care"),
                            ("Nursing care", "Nursing care"),
                            ("Medical social services", "Medical social services"),
                            (
                                "Homemaker or basic assistance care",
                                "Homemaker or basic assistance care",
                            ),
                        ],
                        default="Doctor care",
                        max_length=50,
                    ),
                ),
                ("day", models.DateField(default=datetime.datetime.now)),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("3 PM", "3 PM"),
                            ("3:30 PM", "3:30 PM"),
                            ("4 PM", "4 PM"),
                            ("4:30 PM", "4:30 PM"),
                            ("5 PM", "5 PM"),
                            ("5:30 PM", "5:30 PM"),
                            ("6 PM", "6 PM"),
                            ("6:30 PM", "6:30 PM"),
                            ("7 PM", "7 PM"),
                            ("7:30 PM", "7:30 PM"),
                        ],
                        default="3 PM",
                        max_length=10,
                    ),
                ),
                (
                    "time_ordered",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
