# Generated by Django 4.1 on 2023-05-13 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("6ec1ea1a-05fd-454e-ab99-3788ec77f7c1"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
