# Generated by Django 4.1 on 2023-05-15 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                choices=[
                    ("1", "Adult Cardiology"),
                    ("2", "Adult Neurology"),
                    ("3", "Anaesthesia"),
                    ("4", "Anaesthesia and Critical Care Medicine"),
                    ("5", "Dermatology"),
                    ("6", "Ear, Nose and Throat (ENT)"),
                    ("7", "General Surgery"),
                    ("8", "Gynaecology / Laparoscopic / Obsterics"),
                    ("9", "Interventional Cardiology"),
                    ("10", "Nephrology"),
                    ("11", "Ophthalmology"),
                    ("12", "Paediatrics and Child Health"),
                    ("13", "Pain Management"),
                    ("14", "Physician /Internal Medicine"),
                    ("15", "Radiology"),
                ],
                default="Physician / Internal Medicine",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="image",
            field=models.ImageField(upload_to="profiles", verbose_name="Images"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="role",
            field=models.CharField(
                choices=[
                    ("1", "Adult Cardiology"),
                    ("2", "Adult Neurology"),
                    ("3", "Anaesthesia"),
                    ("4", "Anaesthesia and Critical Care Medicine"),
                    ("5", "Dermatology"),
                    ("6", "Ear, Nose and Throat (ENT)"),
                    ("7", "General Surgery"),
                    ("8", "Gynaecology / Laparoscopic / Obsterics"),
                    ("9", "Interventional Cardiology"),
                    ("10", "Nephrology"),
                    ("11", "Ophthalmology"),
                    ("12", "Paediatrics and Child Health"),
                    ("13", "Pain Management"),
                    ("14", "Physician /Internal Medicine"),
                    ("15", "Radiology"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("d8dcc062-156d-46ea-9d07-21e63155a023"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
