# Generated by Django 4.1 on 2023-05-12 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="username",
        ),
        migrations.AddField(
            model_name="doctor",
            name="password",
            field=models.CharField(
                default="password",
                max_length=30,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=8,
                        message="Please ensure the password is at least 8 characters",
                    ),
                    django.core.validators.RegexValidator(regex="^password"),
                ],
            ),
        ),
    ]
