# Generated by Django 4.1 on 2023-05-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_patient_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="is_superuser",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
