# Generated by Django 4.1 on 2023-05-13 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_persona_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("26d62e32-8335-45c4-938c-569df2ccc477"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
