# Generated by Django 4.1 on 2023-05-15 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_persona_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("274fe64f-09d2-465d-af1d-e2c78275dbde"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
