# Generated by Django 4.1 on 2023-05-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_patient_is_staff_alter_patient_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Non-Binary", "Non-Binary"),
                    ("Prefer Not To Say", "Prefer Not To Say"),
                ],
                default="Prefer Not To Say",
                max_length=20,
            ),
        ),
    ]
