# Generated by Django 4.1 on 2023-05-14 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_persona_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="note",
        ),
        migrations.AlterField(
            model_name="persona",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("7d59a5da-c0be-4068-819e-b557adbadffc"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
