# Generated by Django 4.1 on 2023-05-17 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_persona_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                choices=[
                    ("Adult Cardiology", "Adult Cardiology"),
                    ("Adult Neurology", "Adult Neurology"),
                    ("Anaesthesia", "Anaesthesia"),
                    (
                        "Anaesthesia and Critical Care Medicine",
                        "Anaesthesia and Critical Care Medicine",
                    ),
                    ("Dermatology", "Dermatology"),
                    ("Ear, Nose and Throat (ENT)", "Ear, Nose and Throat (ENT)"),
                    ("General Surgery", "General Surgery"),
                    (
                        "Gynaecology / Laparoscopic / Obsterics",
                        "Gynaecology / Laparoscopic / Obsterics",
                    ),
                    ("Interventional Cardiology", "Interventional Cardiology"),
                    ("Nephrology", "Nephrology"),
                    ("Ophthalmology", "Ophthalmology"),
                    ("Paediatrics and Child Health", "Paediatrics and Child Health"),
                    ("Pain Management", "Pain Management"),
                    ("Physician /Internal Medicine", "Physician /Internal Medicine"),
                    ("Radiology", "Radiology"),
                ],
                default="Physician / Internal Medicine",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="role",
            field=models.CharField(
                choices=[
                    ("Adult Cardiology", "Adult Cardiology"),
                    ("Adult Neurology", "Adult Neurology"),
                    ("Anaesthesia", "Anaesthesia"),
                    (
                        "Anaesthesia and Critical Care Medicine",
                        "Anaesthesia and Critical Care Medicine",
                    ),
                    ("Dermatology", "Dermatology"),
                    ("Ear, Nose and Throat (ENT)", "Ear, Nose and Throat (ENT)"),
                    ("General Surgery", "General Surgery"),
                    (
                        "Gynaecology / Laparoscopic / Obsterics",
                        "Gynaecology / Laparoscopic / Obsterics",
                    ),
                    ("Interventional Cardiology", "Interventional Cardiology"),
                    ("Nephrology", "Nephrology"),
                    ("Ophthalmology", "Ophthalmology"),
                    ("Paediatrics and Child Health", "Paediatrics and Child Health"),
                    ("Pain Management", "Pain Management"),
                    ("Physician /Internal Medicine", "Physician /Internal Medicine"),
                    ("Radiology", "Radiology"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("1a6e749e-02fc-4658-8dd3-60f607ddbdd9"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
