# Generated by Django 4.1 on 2023-05-14 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_remove_appointment_note_alter_persona_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="price",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="app_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                choices=[
                    ("1", "Adult Cardiology"),
                    ("2", "Adult Neurology"),
                    ("3", "Anaesthesia"),
                    ("4", "Anaesthesia and Critical Care Medicine"),
                    ("5", "Dermatology"),
                    ("6", "Ear, Nose and Throat (ENT)"),
                    ("7", "General Surgery"),
                    ("8", "Gynaecology / Laparoscopic / Obsterics"),
                    ("9", "Interventional Cardiology"),
                    ("10", "Nephrology"),
                    ("11", "Ophthalmologist"),
                    ("12", "Paediatrics and Child Health"),
                    ("13", "Pain Management"),
                    ("14", "Physician /Internal Medicine"),
                    ("15", "Radiology"),
                ],
                default="Physician / Internal Medicine",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.CharField(
                choices=[
                    ("8 AM", "8 AM"),
                    ("9 AM", "9 AM"),
                    ("10 AM", "10 AM"),
                    ("11 AM", "11 AM"),
                    ("11:30 AM", "11:30 AM"),
                    ("12 PM", "12 PM"),
                    ("1:30 PM", "1:30 PM"),
                    ("2 PM", "2 PM"),
                ],
                default="3 PM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="uuid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="role",
            field=models.CharField(
                choices=[
                    ("1", "Adult Cardiology"),
                    ("2", "Adult Neurology"),
                    ("3", "Anaesthesia"),
                    ("4", "Anaesthesia and Critical Care Medicine"),
                    ("5", "Dermatology"),
                    ("6", "Ear, Nose and Throat (ENT)"),
                    ("7", "General Surgery"),
                    ("8", "Gynaecology / Laparoscopic / Obsterics"),
                    ("9", "Interventional Cardiology"),
                    ("10", "Nephrology"),
                    ("11", "Ophthalmologist"),
                    ("12", "Paediatrics and Child Health"),
                    ("13", "Pain Management"),
                    ("14", "Physician /Internal Medicine"),
                    ("15", "Radiology"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("b891b5f3-49cd-410c-b82a-41f4bc6f9b8d"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
