# Generated by Django 4.1 on 2023-05-17 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_alter_persona_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("4a0be2f4-2062-426c-b6e6-bf0958ceea82"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
