# Generated by Django 4.1 on 2023-05-18 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_alter_persona_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="persona",
            name="uuid",
            field=models.UUIDField(
                auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
