# Generated by Django 4.1 on 2023-05-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_appointment_completed_alter_persona_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="note",
            field=models.TextField(default=""),
        ),
    ]
