# Generated by Django 4.1 on 2023-05-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_alter_notification_notif_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="persona",
            new_name="persona_id",
        ),
    ]
