# Generated by Django 4.1 on 2023-05-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_rename_persona_notification_persona_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
