# Generated by Django 4.1 on 2023-05-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_alter_notification_notif_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_id",
            field=models.IntegerField(
                blank=True, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
