# Generated by Django 4.1 on 2023-05-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_alter_notification_notif_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
