# Generated by Django 4.1 on 2023-05-19 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0017_alter_notification_notif_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid1, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_id",
            field=models.IntegerField(),
        ),
    ]
