# Generated by Django 4.1 on 2023-05-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_remove_notification_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.CharField(
                choices=[
                    ("8:00 AM", "8:00 AM"),
                    ("9:00 AM", "9:00 AM"),
                    ("10:00 AM", "10:00 AM"),
                    ("11:00 AM", "11:00 AM"),
                    ("11:30 AM", "11:30 AM"),
                    ("12:00 PM", "12:00 PM"),
                    ("1:30 PM", "1:30 PM"),
                    ("2:00 PM", "2:00 PM"),
                ],
                max_length=10,
            ),
        ),
    ]
